version: "3"

services:
  ploi-roadmap:
    image: zurdi15/romm:1.6.2
    container_name: ploi-roadmap
    environment:
      - APP_ENV=production
      - APP_NAME="Ploi Roadmap"
      - APP_KEY=base64-key
      - APP_ENV=local
      - APP_DEBUG=false
      - APP_ADMIN_NOTIFICATIONS=true
      - APP_LOCALE=en
      - APP_TIMEZONE=America/New_York
      - DB_CONNECTION=mysql
      - DB_HOST=ploi-roadmap-db 
      - DB_PORT=3306 
      - DB_DATABASE=ploi-roadmap
      - DB_USERNAME=ploi
      - DB_PASSWORD=${PLOI_MYSQL_PASSWORD} 
      #- MAIL_MAILER=smtp
      #- MAIL_HOST=mailhog
      #- MAIL_PORT=1025
      #- MAIL_USERNAME=null
      #- MAIL_PASSWORD=null
      #- MAIL_ENCRYPTION=null
      #- MAIL_FROM_ADDRESS="hello@example.com"
      #- MAIL_FROM_NAME="${APP_NAME}"
    restart: unless-stopped
    volumes:
      - ./app-data:/app
      - ./vendor-data:/vendor
    ports:
      - 8080:80
    depends_on:
      - ploi-roadmap-db
    networks:
      - roadmap

  ploi-roadmap-db:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: ploi-roadmap-db
    environment:
      - MYSQL_ROOT_PASSWORD=${PLOI_MYSQL_PASSWORD}
      - MYSQL_DATABASE=ploi-roadmap
      - MYSQL_USER=ploi
      - MYSQL_PASSWORD=${PLOI_MYSQL_PASSWORD}
    volumes:
      - ./mysql/config:/config
    restart: "unless-stopped"
    networks:
      - roadmap

networks:
  roadmap:
    driver: bridge